import type { Metadata } from "next";

import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import AppWalletProvider from "@/components/AppWalletProvider";
import { Appbar } from "@/components/Appbar";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppWalletProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <ClerkProvider>
              <div>
                <Appbar />
                {children}
                <Toaster />
              </div>
            </ClerkProvider>
          </ThemeProvider>
        </AppWalletProvider>
      </body>
    </html>
  );
}
